// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhxLq-c-fmQQS2t3qbZcdgXll6Wj425SA',
    appId: '1:568807938210:web:ea849b08458f48d13e5ffb',
    messagingSenderId: '568807938210',
    projectId: 'rempah-8eb72',
    authDomain: 'rempah-8eb72.firebaseapp.com',
    storageBucket: 'rempah-8eb72.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK_ia9--__L7udEhRxulmEnF72Rr-WS8w',
    appId: '1:568807938210:android:26f252aa65c9f3273e5ffb',
    messagingSenderId: '568807938210',
    projectId: 'rempah-8eb72',
    storageBucket: 'rempah-8eb72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJSlzZ78TW17ZPVphba25ChXfzXQ6SfZI',
    appId: '1:568807938210:ios:0d64ca43a3fa2e6f3e5ffb',
    messagingSenderId: '568807938210',
    projectId: 'rempah-8eb72',
    storageBucket: 'rempah-8eb72.firebasestorage.app',
    iosBundleId: 'com.example.rempah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJSlzZ78TW17ZPVphba25ChXfzXQ6SfZI',
    appId: '1:568807938210:ios:0d64ca43a3fa2e6f3e5ffb',
    messagingSenderId: '568807938210',
    projectId: 'rempah-8eb72',
    storageBucket: 'rempah-8eb72.firebasestorage.app',
    iosBundleId: 'com.example.rempah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhxLq-c-fmQQS2t3qbZcdgXll6Wj425SA',
    appId: '1:568807938210:web:c6053abd3310fc153e5ffb',
    messagingSenderId: '568807938210',
    projectId: 'rempah-8eb72',
    authDomain: 'rempah-8eb72.firebaseapp.com',
    storageBucket: 'rempah-8eb72.firebasestorage.app',
  );
}
